name: floodenv2
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.10=py311h5082efb_0
  - aiohttp-retry=2.8.3=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amqp=5.2.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - aom=3.5.0=h63175ca_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asyncssh=2.18.0=pyhd8ed1ab_0
  - atpublic=5.0=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - backports.zoneinfo=0.2.1=py311h1ea47a8_9
  - billiard=4.2.1=py311he736701_0
  - blas=1.0=mkl
  - blosc=1.21.5=hdccc3a2_0
  - boost-cpp=1.78.0=h9f4b32c_4
  - boto3=1.35.60=pyhd8ed1ab_0
  - botocore=1.35.60=pyge310_1234567_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py311h12c1d0e_9
  - bzip2=1.0.8=h2466b09_7
  - c-blosc2=2.12.0=h183a6f4_0
  - ca-certificates=2024.12.14=h56e8100_0
  - cairo=1.16.0=h0ac17fb_1012
  - celery=5.4.0=pyhd8ed1ab_1
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py311he736701_0
  - cfitsio=4.2.0=h9ebe7e4_0
  - cftime=1.6.4=py311h0a17f05_1
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - click-didyoumean=0.3.1=pyhd8ed1ab_0
  - click-plugins=1.1.1=py_0
  - click-repl=0.3.0=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - configobj=5.0.9=pyhd8ed1ab_0
  - contourpy=1.3.0=py311h3257749_2
  - cryptography=42.0.2=py311h7cb4080_0
  - cudatoolkit=11.8.0=h09e9e62_13
  - curl=8.1.2=h68f0423_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dictdiffer=0.9.0=pyhd8ed1ab_0
  - diskcache=5.6.3=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - dpath=2.2.0=pyha770c72_0
  - dulwich=0.22.5=py311h533ab2d_0
  - dvc=3.56.0=pyhd8ed1ab_0
  - dvc-data=3.16.7=pyhd8ed1ab_0
  - dvc-http=2.32.0=pyhd8ed1ab_0
  - dvc-objects=5.1.0=pyhd8ed1ab_1
  - dvc-render=1.0.2=pyhd8ed1ab_0
  - dvc-studio-client=0.21.0=pyhd8ed1ab_0
  - dvc-task=0.40.2=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.6.4=he0c23c2_0
  - fiona=1.9.1=py311ha4db88c_0
  - flatten-dict=0.4.2=pyhd8ed1ab_1
  - flufl.lock=8.1.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py311h5082efb_1
  - freetype=2.12.1=hdaf720e_2
  - freexl=1.0.6=h67ca5e6_1
  - fribidi=1.0.10=h8d14728_0
  - frozenlist=1.5.0=py311he736701_0
  - funcy=2.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_0
  - gdal=3.6.2=py311h4bd9738_9
  - geographiclib=2.0=pyhd8ed1ab_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.11.1=h1537add_0
  - geotiff=1.7.1=hc256dc0_6
  - getopt-win32=0.1=hcfcfb64_1
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h64bf75a_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glib=2.78.1=h12be248_0
  - glib-tools=2.78.1=h12be248_0
  - grandalf=0.7=pyhd8ed1ab_0
  - graphite2=1.3.13=h63175ca_1003
  - graphviz=8.1.0=h51cb2cd_0
  - gst-plugins-base=1.22.7=h001b923_0
  - gstreamer=1.22.7=hb4038d2_0
  - gto=1.7.1=pyhd8ed1ab_1
  - gts=0.7.6=h6b5321d_4
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=6.0.0=he256f1b_0
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.12.2=nompi_h57737ce_101
  - hpack=4.0.0=pyh9f0ad1d_0
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=70.1=h0e60522_0
  - idna=3.10=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py311h8318e5d_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2023.2.0=h57928b3_50497
  - iterative-telemetry=0.0.9=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - jxrlib=1.1=hcfcfb64_3
  - kealib=1.5.0=h61be68b_0
  - kiwisolver=1.4.7=py311h3257749_0
  - kombu=5.4.1=py311h1ea47a8_0
  - krb5=1.20.1=heb0366b_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240116.2=cxx17_he0c23c2_1
  - libaec=1.1.3=h63175ca_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libavif=0.11.1=ha7b97ba_2
  - libblas=3.9.0=20_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=20_win64_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.17=hcfcfb64_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libgcc=14.2.0=h1383e82_1
  - libgd=2.3.3=ha43c60c_1
  - libgdal=3.6.2=h221c0cb_9
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libgit2=1.8.4=h66fae2d_0
  - libglib=2.78.1=he8f3873_0
  - libgomp=14.2.0=h1383e82_1
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=20_win64_mkl
  - libnetcdf=4.9.1=nompi_hc41bf00_101
  - libogg=1.3.5=h2466b09_0
  - libpng=1.6.44=h3ca93ac_0
  - libpq=15.3=ha9684e8_1
  - libprotobuf=4.25.3=h47a098d_1
  - librttopo=1.1.0=he22b5cd_12
  - libspatialite=5.0.1=hfdcade0_23
  - libsqlite=3.47.0=h2466b09_1
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.5.0=hf8721a0_2
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_8
  - libxcb=1.13=0
  - libxml2=2.13.4=h442d1da_2
  - libzip=1.10.1=h1d365fa_3
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - lz4-c=1.9.4=hcfcfb64_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - matplotlib=3.9.1=py311h1ea47a8_1
  - matplotlib-base=3.9.1=py311h8f1b1e4_2
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.0=py311h8c5a130_1
  - mkl_fft=1.3.11=py311h827c3e9_0
  - mkl_random=1.2.8=py311h97a4ddd_0
  - multidict=6.1.0=py311h5082efb_1
  - munch=4.0.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - netcdf4=1.6.3=nompi_py311hd70422a_100
  - numpy=1.26.4=py311hdab7c0b_0
  - numpy-base=1.26.4=py311hd01c5d8_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.7=h2466b09_0
  - orjson=3.10.11=py311h533ab2d_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py311hcf9f919_1
  - pango=1.50.14=hdffb7b3_0
  - pathlib2=2.3.7.post1=py311h1ea47a8_4
  - pathspec=0.12.1=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pillow=9.4.0=py311h76d9071_1
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.43.4=h63175ca_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - poppler=23.03.0=h183ae7b_0
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=h96452e4_1
  - proj=9.1.1=heca977f_2
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - propcache=0.2.0=py311he736701_2
  - protobuf=4.25.3=py311hffb1a97_1
  - psutil=6.1.0=py311he736701_0
  - pthread-stubs=0.4=h0e40799_1002
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.9.2=pyhd8ed1ab_0
  - pydantic-core=2.23.4=py311h533ab2d_0
  - pydot=3.0.2=py311h1ea47a8_0
  - pygit2=1.15.1=py311he736701_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - pygtrie=2.5.0=pyhd8ed1ab_0
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyproj=3.5.0=py311h36482e4_0
  - pyqt=5.15.9=py311h125bc19_5
  - pyqt5-sip=12.12.2=py311h12c1d0e_5
  - pysocks=1.7.1=pyh0701188_6
  - python=3.11.6=h2628c8c_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-gssapi=1.8.2=py311hf92330d_2
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=307=py311hda3d55a_3
  - pywin32-on-windows=0.1.0=pyh07e9846_2
  - pyyaml=6.0.2=py311he736701_1
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.8=h720456b_6
  - rasterio=1.3.6=py311hc06ee40_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rioxarray=0.17.0=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py311he736701_1
  - ruamel.yaml.clib=0.2.8=py311he736701_1
  - s3transfer=0.10.3=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py311hdcb8d17_1
  - scipy=1.14.1=py311hf16d85f_1
  - scmrepo=3.3.8=pyhd8ed1ab_0
  - semver=3.0.2=pyhd8ed1ab_0
  - sentry-sdk=2.18.0=pyhd8ed1ab_0
  - setproctitle=1.3.3=py311he736701_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - shapely=2.0.1=py311habfe8a2_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - shortuuid=1.0.13=pyhd8ed1ab_0
  - shtab=1.7.1=pyhd8ed1ab_0
  - sip=6.7.12=py311h12c1d0e_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=hfb803bf_1
  - snuggs=1.4.7=pyhd8ed1ab_1
  - sqlite=3.47.0=h2466b09_1
  - sqltrie=0.11.1=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.7.0=h91493d7_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2023.8.12=pyhd8ed1ab_0
  - tiledb=2.13.2=h3132609_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - tomlkit=0.13.2=pyha770c72_0
  - tornado=6.4.1=py311he736701_1
  - tqdm=4.67.0=pyhd8ed1ab_0
  - typer=0.13.0=pyhd8ed1ab_0
  - typer-slim=0.13.0=pyhff2d567_0
  - typer-slim-standard=0.13.0=hd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py311he736701_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.3=h8a93ad2_22
  - vc14_runtime=14.40.33810=hcc2c482_22
  - vine=5.1.0=pyhd8ed1ab_0
  - voluptuous=0.15.2=pyhd8ed1ab_1
  - vs2015_runtime=14.40.33810=h3bf8584_22
  - wandb=0.18.5=py311h533ab2d_2
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - xarray=2024.10.0=pyhd8ed1ab_0
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.11=h0e40799_1
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zc.lockfile=3.0.post1=pyhd8ed1ab_0
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstandard=0.23.0=py311h53056dc_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - efficientnet-pytorch==0.7.1
      - filelock==3.13.1
      - fsspec==2024.2.0
      - git-filter-repo==2.47.0
      - huggingface-hub==0.26.2
      - iglovikov-helper-functions==0.0.53
      - imagecorruptions==1.1.2
      - imageio==2.36.0
      - jinja2==3.1.3
      - jpeg4py==0.1.4
      - lazy-loader==0.4
      - lightning-utilities==0.11.8
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - opencv-python==4.10.0.84
      - pretrainedmodels==0.7.4
      - pytorch-lightning==2.4.0
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - segmentation-models-pytorch==0.3.4
      - surface-distance==0.1
      - sympy==1.13.1
      - timm==0.9.7
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchmetrics==1.5.2
      - torchvision==0.20.1+cu118
      - yarl==1.17.1
prefix: C:\Users\alwebb\AppData\Local\miniconda3\envs\floodenv2
