# INFERENCE

threshold:
input TSX hh folder:
ourput prediction folder:





# data root : 'Y:\Users\AI_Flood_Service\data'
# polygon directory : 'Y:\Users\AI_Flood_Service\polygons'
# analysis extent: 'Y:\Users\AI_Flood_Service\impact_layers\Boundary\BGD\adm0_BGD.shp'

# model dir : 'Y:\Users\AI_Flood_Service\models'
# model name : 'model_1'

# download parameters: 

#   username : unosat
#   password : Building597
#   TimeDelta :  1
#   StartDate (YYYYMMDD) : 
#   EndDate (YYYYMMDD)  : 


# inference parameters:

#   threshold: 0.8
#   offset x: 128 
#   offset y: 128
#   country code: 'BGD'

# post processing paramenters:

#   layers repository: 'Y:\Users\AI_Flood_Service\impact_layers'
#   landcover source: 'ESA+JRC' # ESA, JRC, ESRI, ESA+JRC 


# visualization paramenters:

#   esri server: \\cernunosat74\FloodAI_Output\AI20240502BGD
#   download server: \\eosproject-smb\eos\project\u\unosat-ai\www\files\BD\AI20240502BGD
  # HITL delay: 0
  
